wandb_version: 1

device:
  desc: null
  value: cuda:0
data_path:
  desc: null
  value: datasets
keypoints_path:
  desc: null
  value: ./spinopelvic_keypoints.json
person_det:
  desc: null
  value: null
fixed_size:
  desc: null
  value:
  - 512
  - 512
num_joints:
  desc: null
  value: 4
output_dir:
  desc: null
  value: save_weights/exp29
resume:
  desc: null
  value: ''
start_epoch:
  desc: null
  value: 0
epochs:
  desc: null
  value: 20
lr_steps:
  desc: null
  value:
  - 100
  - 150
lr_gamma:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.0009
weight_decay:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 28
amp:
  desc: null
  value: false
savebest:
  desc: null
  value: 1
log_path:
  desc: null
  value: runs/exp24
with_FFCA:
  desc: null
  value: true
optimizer:
  desc: null
  value: adamw
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701156895.924312
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 17
      - 19
      - 23
      - 37
      4: 3.9.18
      5: 0.16.0
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.0009
